### ISSUE TITLE
Error while trying to use Keras Conv2D with groups

### ISSUE THREAD

**Issue by Astrych** [intel/intel-extension-for-tensorflow#36]
I'm using
```
intel-extension-for-tensorflow==1.2.0
tensorflow==2.12.0
keras==2.12.0
```

and this example code:
```python
import tensorflow as tf

keras = tf.keras
layers = keras.layers
Model = keras.Model
cifar10 = keras.datasets.cifar10
Adam = keras.optimizers.Adam
SparseCategoricalCrossentropy = keras.losses.SparseCategoricalCrossentropy
SparseCategoricalAccuracy = keras.metrics.SparseCategoricalAccuracy


(x_train, y_train), (x_test, y_test) = cifar10.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

dim = 3

inputs = layers.Input(shape=(32, 32, 3))
x = layers.Conv2D(dim, 5, groups=dim, padding='same')(inputs)
x = layers.Flatten()(x)
outputs = layers.Dense(10)(x)

model = Model(inputs=inputs, outputs=outputs)

model.compile(
    optimizer=Adam(), 
    loss=SparseCategoricalCrossentropy(from_logits=True), 
    metrics=[SparseCategoricalAccuracy()]
)

model.fit(x_train, y_train, batch_size=32, validation_data=(x_test, y_test))
```

produce following error:
```
  2023-05-28 16:13:38.918983: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-28 16:13:40.586299: I itex/core/devices/gpu/itex_gpu_runtime.cc:129] Selected platform: Intel(R) Level-Zero
2023-05-28 16:13:40.586348: I itex/core/devices/gpu/itex_gpu_runtime.cc:154] number of sub-devices is zero, expose root device.
2023-05-28 16:13:41.353075: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform XPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-05-28 16:13:41.353127: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:XPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: XPU, pci bus id: <undefined>)
2023-05-28 16:13:42.520439: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type XPU is enabled.
2023-05-28 16:13:42.601207: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:362 : NOT_FOUND: could not find registered platform with id: (nil)
2023-05-28 16:13:42.601253: I tensorflow/core/common_runtime/executor.cc:1197] [/job:localhost/replica:0/task:0/device:XPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): NOT_FOUND: could not find registered platform with id: (nil)
         [[{{node model/conv2d/PartitionedCall}}]]
Traceback (most recent call last):
  File "/home/me/test/TEST.py", line 27, in <module>
    model.fit(x_train, y_train, batch_size=32, validation_data=(x_test, y_test))
  File "/opt/miniconda3/envs/predict-ai/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/opt/miniconda3/envs/predict-ai/lib/python3.10/site-packages/tensorflow/python/eager/execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.NotFoundError: Graph execution error:

Detected at node 'model/conv2d/PartitionedCall' defined at (most recent call last):
    File "/home/me/test/TEST.py", line 27, in <module>
      model.fit(x_train, y_train, batch_size=32, validation_data=(x_test, y_test))
    File "/opt/miniconda3/envs/predict-ai/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/opt/miniconda3/envs/predict-ai/lib/python3.10/site-packages/keras/engine/training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "/opt/miniconda3/envs/predict-ai/lib/python3.10/site-packages/keras/engine/training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "/opt/miniconda3/envs/predict-ai/lib/python3.10/site-packages/keras/engine/training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/opt/miniconda3/envs/predict-ai/lib/python3.10/site-packages/keras/engine/training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "/opt/miniconda3/envs/predict-ai/lib/python3.10/site-packages/keras/engine/training.py", line 1050, in train_step
      y_pred = self(x, training=True)
    File "/opt/miniconda3/envs/predict-ai/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/opt/miniconda3/envs/predict-ai/lib/python3.10/site-packages/keras/engine/training.py", line 558, in __call__
      return super().__call__(*args, **kwargs)
    File "/opt/miniconda3/envs/predict-ai/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/opt/miniconda3/envs/predict-ai/lib/python3.10/site-packages/keras/engine/base_layer.py", line 1145, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/opt/miniconda3/envs/predict-ai/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "/opt/miniconda3/envs/predict-ai/lib/python3.10/site-packages/keras/engine/functional.py", line 512, in call
      return self._run_internal_graph(inputs, training=training, mask=mask)
    File "/opt/miniconda3/envs/predict-ai/lib/python3.10/site-packages/keras/engine/functional.py", line 669, in _run_internal_graph
      outputs = node.layer(*args, **kwargs)
    File "/opt/miniconda3/envs/predict-ai/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/opt/miniconda3/envs/predict-ai/lib/python3.10/site-packages/keras/engine/base_layer.py", line 1145, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/opt/miniconda3/envs/predict-ai/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "/opt/miniconda3/envs/predict-ai/lib/python3.10/site-packages/keras/layers/convolutional/base_conv.py", line 286, in call
      outputs = self._jit_compiled_convolution_op(
Node: 'model/conv2d/PartitionedCall'
could not find registered platform with id: (nil)
         [[{{node model/conv2d/PartitionedCall}}]] [Op:__inference_train_function_605]
```

BTW: it works with CPU.

**Comment by guizili0** [comment]
@Astrych ITEX currently did not support XLA but Keras force group conv to run in XLA.
For more detail, you can find https://github.com/keras-team/keras/issues/18180
For local WA, you can remove the Keras WA for CPU.
We are trying to find a proper way to solve this issue.

**Comment by srinarayan-srikanthan** [comment]
@Astrych I hope you were able to get the WA mentioned above. If not remove the if else block at https://github.com/keras-team/keras/blob/master/keras/layers/convolutional/base_conv.py#L285 and just use outputs = self.convolution_op(inputs, self.kernel) . This should resolve the issue you are facing.  We are following this up with keras team on the thread attached above and should have a permanent fix.

**Comment by Astrych** [comment]
@srinarayan-srikanthan Yes thanks. I managed to work it out for now.
