### ISSUE TITLE
Double precision operations do not fall back to CPU

### ISSUE THREAD

**Issue by aplund** [intel/intel-extension-for-tensorflow#60]
I'm not sure if this is a tensorflow issue, or an issue for this extension, but I somewhat expected float64 operations to fall back to CPU if the XPU doesn't support double precision.

This is my test script.  By forcing the CPU, it works.  Otherwise it does not.

```
import tensorflow as tf
import intel_extension_for_tensorflow as itex

print(itex.__version__)
print(tf.config.list_physical_devices())

tf.random.set_seed(1)

with tf.device("CPU"):
    a = tf.random.normal([100, 100], dtype=tf.float64)
    print(a)

b = tf.random.normal([100, 100], dtype=tf.float64)
print(b)
```

My output is as follows:

```
2024-02-07 12:10:31.501383: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-02-07 12:10:31.520130: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-07 12:10:32.243362: I itex/core/wrapper/itex_cpu_wrapper.cc:70] Intel Extension for Tensorflow* AVX2 CPU backend is loaded.
2024-02-07 12:10:32.525588: I itex/core/wrapper/itex_gpu_wrapper.cc:35] Intel Extension for Tensorflow* GPU backend is loaded.
2024-02-07 12:10:32.572263: I itex/core/devices/gpu/itex_gpu_runtime.cc:129] Selected platform: Intel(R) Level-Zero
2024-02-07 12:10:32.572437: I itex/core/devices/gpu/itex_gpu_runtime.cc:154] number of sub-devices is zero, expose root device.
2.14.0.2
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:XPU:0', device_type='XPU')]
2024-02-07 12:10:34.198031: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform XPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-02-07 12:10:34.198172: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:XPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: XPU, pci bus id: <undefined>)
tf.Tensor(
[[ 0.4459007   1.43996715 -1.38644356 ... -0.56132069  0.60606447
  -0.03492888]
 [-0.75159453 -0.26010379 -0.37447672 ... -0.66846839 -0.43303597
   1.08628045]
 [ 1.15986581 -0.54390388  0.26037126 ... -1.05720308  1.30973215
   1.94999804]
 ...
 [ 0.82583929 -0.08518099 -0.27259486 ...  0.41736816 -0.89526063
   0.16398707]
 [-0.95394833 -2.18525502 -0.7335378  ... -0.87173428  0.26623126
  -0.0166979 ]
 [ 0.07828288  0.11658528  1.62267529 ... -0.7764499  -0.53504971
   1.04393415]], shape=(100, 100), dtype=float64)
2024-02-07 12:10:35.643851: W itex/core/utils/op_kernel.cc:360] Aborted: RandomStandardNormal op uses fp64 data type, while fp64 instructions are not supported on the platform.
Traceback (most recent call last):
  File "/home/lund/.cache/tmp/itex-bugs/one.py", line 13, in <module>
    b = tf.random.normal([100, 100], dtype=tf.float64)
  File "/home/lund/.pyenv/versions/mrmustard-0.7/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/lund/.pyenv/versions/mrmustard-0.7/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 5883, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.AbortedError: {{function_node __wrapped__RandomStandardNormal_device_/job:localhost/replica:0/task:0/device:XPU:0}} RandomStandardNormal op uses fp64 data type, while fp64 instructions are not supported on the platform. [Op:RandomStandardNormal] name:
```

**Comment by guizili0** [comment]
@aplund seems you are using intel FLEX GPU or ARC, this HW did not have FP64 support in HW side, so we disable FP64 support on these platforms.

**Comment by guizili0** [comment]
@aplund Yes, we want to customer aware that this system did not support FP64 instead of fallback to CPU silently. That would cause customer get wrong information about this system has performance issue.

**Comment by aplund** [comment]
OK.  So the solution to run existing double precision code rewriting with context managers is to uninstall the extension?

**Comment by guizili0** [comment]
@aplund please add below environment variable due to no HW support on FP64
```
export NEOReadDebugKeys=1
export OverrideDefaultFP64Settings=1
export IGC_EnableDPEmulation=1
```

**Comment by aplund** [comment]
> @aplund please add below environment variable due to no HW support on FP64
> 
> ```
> export NEOReadDebugKeys=1
> export OverrideDefaultFP64Settings=1
> export IGC_EnableDPEmulation=1
> ```

This works.
